"""Add schedule_payment_date to orders

Revision ID: 28569963ab20
Revises: 230ad448bc35
Create Date: 2024-11-30 20:33:34.648177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28569963ab20'
down_revision = '230ad448bc35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('schedule_payment_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('schedule_payment_date')
        batch_op.drop_column('delivery_status')

    # ### end Alembic commands ###
