"""added role functionality

Revision ID: 5797876c911c
Revises: 04b086c4a11c
Create Date: 2024-12-02 17:58:50.984975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5797876c911c'
down_revision = '04b086c4a11c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('admin', 'manager', 'user', name='role_enum'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('admin', 'manager', 'user', name='role_enum'),
               nullable=True)

    # ### end Alembic commands ###
