"""unique name and email for client validation

Revision ID: 92abfbe6f925
Revises: 5797876c911c
Create Date: 2024-12-02 19:06:11.786698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92abfbe6f925'
down_revision = '5797876c911c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
