"""Add payment_staus  to orders

Revision ID: fcc4c2cb9fa9
Revises: 28569963ab20
Create Date: 2024-11-30 20:39:03.363625

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'fcc4c2cb9fa9'
down_revision = '28569963ab20'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE TYPE payment_status_enum AS ENUM ('Pending', 'Overdue', 'Paid')")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.Enum('Pending', 'Overdue', 'Paid', name='payment_status_enum'), nullable=False, server_default='Pending'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
